window.SAA_GLOSSARY = Object.freeze([
  // Security and identity
  ["Permissions Boundary", "IAM principalが取得できる最大権限を制限する境界。権限を付与するpolicyではない。"],
  ["IAM Identity Center", "人間ユーザーのSSOと複数AWSアカウントの権限管理に使うサービス。"],
  ["IAM Access Analyzer", "resource policyを分析し、信頼ゾーン外からアクセス可能なリソースを検出するサービス。"],
  ["Access Analyzer", "IAM Access Analyzerの略称。外部共有や未使用アクセスを分析する。"],
  ["cross-account role", "別AWSアカウントから引き受け、一時認証情報でアクセスさせるIAM role。"],
  ["trust policy", "どのprincipalがIAM roleを引き受けられるかを定義するpolicy。"],
  ["resource policy", "S3 bucketやKMS keyなど、リソース側に設定してアクセスを制御するpolicy。"],
  ["identity policy", "IAM user、group、roleへ付与し、そのidentityが実行できる操作を定義するpolicy。"],
  ["bucket policy", "S3 bucket側に設定するresource policy。principal、action、resource、conditionを定義する。"],
  ["key policy", "KMS keyの管理権限と利用権限を定義する中心的なresource policy。"],
  ["明示Deny", "明示的な拒否。IAM評価ではAllowより優先され、ほかで許可されていても拒否になる。"],
  ["最小権限", "利用者やサービスへ、業務に必要な最小限の権限だけを付与する原則。"],
  ["MFA", "Multi-Factor Authentication。パスワード以外の要素も使う多要素認証。"],
  ["SSO", "Single Sign-On。一度の認証で複数のアプリやAWSアカウントを利用する方式。"],
  ["SAML 2.0 federation", "外部IdPで認証し、一時認証情報でAWS roleを引き受ける連携方式。"],
  ["AWS Organizations", "複数AWSアカウントを組織として一元管理し、OUやSCPを適用するサービス。"],
  ["Organizations", "AWS Organizationsの略称。複数アカウントを組織・OU単位で管理する。"],
  ["permission set", "IAM Identity Centerで、利用者へ割り当てるAWSアカウント権限のひな型。"],
  ["IAM role", "必要時に引き受け、一時認証情報でAWS操作を許可するIAM identity。"],
  ["IAM user", "特定の人またはapplication向けに作る長期的なIAM identity。長期keyの扱いに注意する。"],
  ["ARN", "Amazon Resource Name。AWS resourceを一意に表す識別子。"],
  ["IdP", "Identity Provider。利用者を認証し、SAMLなどでAWSへidentity情報を渡す基盤。"],
  ["OU", "Organizational Unit。Organizations内でAWSアカウントをまとめる管理単位。"],
  ["AWS Directory Service", "Microsoft Active Directory互換のdirectoryやAD Connectorを提供するサービス。"],
  ["SCP", "OrganizationsのService Control Policy。アカウントやOUで利用可能な権限の上限を制限する。"],
  ["IAM", "Identity and Access Management。認証・認可・role・policyを扱う。"],
  ["Cognito", "アプリ利用者のサインアップ、ログイン、ID連携に使う認証サービス。"],
  ["Secrets Manager", "DBパスワードなどの秘密情報を保存し、自動ローテーションにも対応するサービス。"],
  ["Parameter Store", "Systems Managerの設定値・簡易シークレット管理。強いローテーション要件ではSecrets Managerが優先。"],
  ["SecureString", "Systems Manager Parameter StoreでKMS暗号化して保存するparameter type。"],
  ["KMS", "Key Management Service。暗号鍵を作成・管理し、AWSサービスの暗号化に利用する。"],
  ["SSE-KMS", "S3がKMS keyを使ってオブジェクトをサーバー側暗号化する方式。S3とKMS双方の権限が必要。"],
  ["CloudHSM", "専有HSM clusterで暗号鍵とHSMユーザーを利用者自身が管理するサービス。"],
  ["HSM", "Hardware Security Module。暗号鍵を保護し、暗号処理を行う専用ハードウェア。"],
  ["ACM", "AWS Certificate Manager。TLS証明書の発行・管理サービス。"],
  ["TLS", "通信を暗号化し、相手の正当性を証明するプロトコル。HTTPSで利用する。"],

  // Web and threat protection
  ["AWS Firewall Manager", "Organizations配下のWAFやNetwork Firewallなどのsecurity policyを中央管理するサービス。"],
  ["AWS Network Firewall", "VPCのrouteへ組み込み、stateful・stateless ruleで通信を集中検査するマネージドfirewall。"],
  ["Shield Advanced", "高度なDDoS保護、専門支援、DDoS関連コスト保護を提供する有料サービス。"],
  ["Security Hub", "複数AWS security serviceの検出結果とsecurity standard評価を集約するサービス。"],
  ["GuardDuty", "不審通信や認証情報悪用などを検出する脅威検知サービス。"],
  ["Inspector", "EC2、ECR、Lambdaなどの脆弱性を継続評価するサービス。"],
  ["Macie", "S3内の個人情報など機密データを検出するサービス。"],
  ["SQL injection", "入力値を悪用して不正なSQLを実行させるWeb攻撃。AWS WAFで検査・遮断できる。"],
  ["XSS", "Cross-Site Scripting。悪意あるscriptをWebページ上で実行させる攻撃。AWS WAFで対策できる。"],
  ["DDoS", "多数の送信元から大量通信を送り、serviceを利用不能にする分散型サービス妨害攻撃。"],
  ["WAF", "Web Application Firewall。SQL injectionやXSSなどL7のWeb攻撃を検査・遮断する。"],
  ["PII", "Personally Identifiable Information。氏名や識別番号など個人を特定できる情報。"],

  // Audit, monitoring, and governance
  ["CloudWatch billing alarm", "見積請求額metricがthresholdを超えたときに通知するCloudWatch alarm。異常検知とは別物。"],
  ["CloudWatch Metrics", "数値の時系列指標を収集・可視化し、alarmやdashboardに利用するCloudWatch機能。"],
  ["CloudWatch Logs", "applicationやAWS serviceのlogを収集・保存・検索するCloudWatch機能。"],
  ["CloudWatch alarm", "metricが指定条件を満たしたときに通知や自動actionを実行する機能。"],
  ["metric filter", "CloudWatch Logsのlog patternからmetric valueを生成するfilter。"],
  ["CloudWatch", "metric、log、alarm、dashboardを使ってAWS resourceやapplicationを監視するサービス。"],
  ["CloudTrail Insights", "通常と異なるAPI activityを分析して異常な操作傾向を検出するCloudTrail機能。"],
  ["CloudTrail Lake", "CloudTrail eventを長期保存し、SQLで検索・分析するmanaged data lake。"],
  ["log file integrity validation", "CloudTrail logとdigest fileを使い、保存後の変更や削除を暗号学的に検証する機能。"],
  ["CloudTrail", "AWS API呼び出し履歴を記録し、誰がいつ何をしたか追跡する監査証跡サービス。"],
  ["automatic remediation", "AWS Configの非準拠検出を契機に、承認済みの修復処理を自動実行する仕組み。"],
  ["Systems Manager Automation", "AWS resourceの定型運用や修復手順をautomation documentとして実行する機能。"],
  ["AWS Config rule", "AWS resourceの設定が指定条件へ準拠しているか継続評価するrule。"],
  ["AWS Config", "AWS resourceの設定履歴を記録し、ruleで準拠状態を継続評価するサービス。"],
  ["CloudFormation StackSets", "複数account・regionへ同じCloudFormation stackを一括展開する機能。"],
  ["CloudFormation drift detection", "実resourceがCloudFormation templateの定義からずれていないか検出する機能。"],
  ["Trusted Advisor", "cost、security、performanceなどの観点でAWS環境の推奨事項を提示するサービス。"],

  // Networking and delivery
  ["Gateway VPC Endpoint", "S3・DynamoDB向けのVPC Endpoint。NAT GatewayやInternet Gatewayを通さずprivateに到達できる。"],
  ["Interface VPC Endpoint", "PrivateLink型のVPC Endpoint。多くのAWS APIへprivate接続する。"],
  ["Gateway Endpoint", "S3・DynamoDB向けGateway VPC Endpointの短い呼び方。route tableへ経路を追加する。"],
  ["Interface Endpoint", "PrivateLinkを使い、ENI経由でAWS serviceへprivate接続するVPC Endpoint。"],
  ["Gateway Load Balancer", "virtual network appliance群へ通信を透過的に分散するload balancer。"],
  ["VPC Endpoint", "VPC内からAWS serviceへprivate接続する仕組み。Gateway型とInterface型を区別する。"],
  ["VPC Peering", "2つのVPCをprivate IPで直接接続する。transitive routingやCIDR重複には対応しない。"],
  ["Transit Gateway", "多数のVPCやオンプレ接続をhub型に集約するnetwork service。"],
  ["PrivateLink", "Interface Endpointの基盤。VPC間やservice間をroute共有なしでprivateに接続する。"],
  ["NAT Gateway", "private subnetからinternetなどへ外向き通信するためのmanaged NAT。"],
  ["Internet Gateway", "VPCとinternet間の通信経路を提供するVPC component。"],
  ["Site-to-Site VPN", "internet経由でon-premisesとAWSをIPsec暗号化接続するVPN。"],
  ["Direct Connect", "on-premisesとAWSを専用線で接続するservice。VPNより安定した帯域を得やすい。"],
  ["Security Group", "ENI・instance単位のstatefulなvirtual firewall。Allow ruleのみを扱う。"],
  ["NACL", "subnet単位のstateless ACL。AllowとDenyを番号順に評価する。"],
  ["stateful", "接続状態を記憶し、許可した通信への戻り通信を自動で許可する方式。"],
  ["stateless", "接続状態を記憶せず、往路と復路をそれぞれ明示的に許可する方式。"],
  ["ENI", "Elastic Network Interface。EC2などへ付くvirtual network interface。"],
  ["CIDR", "IP address rangeをprefix lengthで表す記法。VPCやsubnet、routeで使用する。"],
  ["private subnet", "internet gatewayへの直接routeを持たないsubnet。外向き通信にはNATなどを使う。"],
  ["subnet", "VPCのIP address rangeをAZ単位に分割したnetwork segment。"],
  ["VPC", "AWS内のvirtual network。subnet、route table、endpointなどと組み合わせる。"],
  ["Global Accelerator", "AWS global networkでTCP・UDP経路を最適化し、固定Anycast IPも使える。"],
  ["CloudFront", "CDN。静的・動的Web contentをedgeから低latencyで配信する。"],
  ["Route 53", "DNS service。name resolution、health check、routing policyを扱う。"],
  ["CDN", "Content Delivery Network。edge locationへcacheし、利用者へ低latencyで配信する仕組み。"],
  ["DNS", "domain nameをIP addressなどへ変換する仕組み。Route 53がmanaged DNSを提供する。"],
  ["TTL", "DNS recordやcacheを保持する時間。短いほど切替は速いがqueryが増える。"],
  ["ALB", "Application Load Balancer。HTTP・HTTPSのL7 load balancer。"],
  ["NLB", "Network Load Balancer。TCP・UDPなどL4、高性能、固定IP要件で使う。"],
  ["L7", "OSI第7層のapplication layer。HTTP pathやheaderなどを扱う。"],
  ["L4", "OSI第4層のtransport layer。TCP・UDP connectionを扱う。"],
  ["AZ", "Availability Zone。1つのregion内で物理的に分離されたdata center群。"],

  // Compute and containers
  ["provisioned concurrency", "Lambdaの初期化済みexecution environmentを事前確保し、cold startを抑える機能。"],
  ["reserved concurrency", "Lambda functionの同時実行数を予約し、同時に上限も設定する機能。"],
  ["cold start", "Lambdaなどで新しいexecution environmentを初期化するときに発生する初回遅延。"],
  ["cluster placement group", "同一AZ内で対応EC2を近接配置し、低latency・高throughput通信を優先する配置方式。"],
  ["partition placement group", "instanceを複数partitionへ分け、hardware障害の影響範囲を分離する配置方式。"],
  ["spread placement group", "少数instanceを別hardwareへ分散し、同時障害リスクを下げる配置方式。"],
  ["Auto Scaling", "負荷や障害に応じてEC2台数などを自動調整する仕組み。"],
  ["ASG", "Auto Scaling Group。EC2 instanceの最小・最大・希望台数を管理するgroup。"],
  ["API Gateway", "REST・HTTP・WebSocket APIを公開・管理するmanaged service。"],
  ["Lambda", "server管理不要のevent-driven execution service。"],
  ["Fargate", "server管理不要でcontainerを実行するcompute engine。"],
  ["ECS", "Elastic Container Service。AWS独自のmanaged container orchestration service。"],
  ["EKS", "Elastic Kubernetes Service。Kubernetesのmanaged control planeを提供する。"],
  ["ECR", "Elastic Container Registry。container imageを保存・配布するmanaged registry。"],
  ["AMI", "Amazon Machine Image。EC2 instanceのOSや設定を含む起動template。"],
  ["Kubernetes", "containerの配置、scale、recoveryを管理するorchestration platform。"],
  ["Helm", "Kubernetes resource群をchartとしてpackage化・展開するtool。"],
  ["EC2", "virtual server。OSやmiddlewareを細かく管理したい場合に使う。"],
  ["HPC", "High Performance Computing。大規模計算を高性能なcompute・network・storageで処理する用途。"],

  // Storage
  ["S3 Server Access Logging", "S3 bucketへのrequest詳細を別のS3 bucketへlog fileとして配信する機能。"],
  ["S3 Transfer Acceleration", "AWS edge networkを使い、遠距離からS3へのupload・downloadを高速化する機能。"],
  ["S3 Cross-Region Replication", "S3 objectを別regionのbucketへ非同期複製する機能。"],
  ["Cross-Region Replication", "resourceやdataを別regionへ複製する構成。S3ではCRRとも呼ぶ。"],
  ["S3 Inventory", "S3 object一覧とmetadataを定期reportとして出力する機能。"],
  ["S3 Access Point", "用途別のhostnameとaccess policyでS3 bucketへのaccessを分離する機能。"],
  ["Data Lifecycle Manager", "EBS snapshotやEBS-backed AMIの作成・保持・削除をpolicyで自動化する機能。"],
  ["S3 Intelligent-Tiering", "access frequencyが読めないS3 dataを自動でstorage tier最適化するclass。"],
  ["S3 Glacier Deep Archive", "長期保管・ほぼ参照しないdata向けの低cost S3 archive tier。"],
  ["Glacier Instant Retrieval", "低頻度archiveをmillisecond単位で取得できるS3 Glacier storage class。"],
  ["Glacier Flexible Retrieval", "数分から数時間のrestoreを選べるS3 Glacier storage class。"],
  ["S3 Storage Lens", "organization・account・bucket横断でS3 usageやactivity metricを可視化する機能。"],
  ["S3 Block Public Access", "S3 bucketやaccount単位でpublic accessを抑止する機能。"],
  ["S3 Object Lock", "S3 objectをWORM要件で一定期間削除・変更不可にする機能。"],
  ["S3 Versioning", "S3 objectの複数versionを保持し、誤削除や上書きから復旧しやすくする機能。"],
  ["Standard-IA", "複数AZへ保存する低頻度access向けS3 storage class。取得料金がかかる。"],
  ["One Zone-IA", "単一AZへ保存する低頻度access向けS3 class。再作成可能なdata向け。"],
  ["WORM", "Write Once Read Many。一度書いたdataを保持期間中に変更・削除できなくする要件。"],
  ["FSx for Windows", "Windows SMB file share向けのmanaged file system。"],
  ["FSx for Lustre", "HPC・ML向けのhigh-performance parallel file system。"],
  ["Storage Gateway", "on-premisesからAWS storageをfile・volume・tapeのように使うservice。"],
  ["DataSync", "on-premisesやAWS storage間のdata migration・sync service。"],
  ["EBS", "EC2にattachするblock storage。"],
  ["EFS", "複数EC2から共有できるmanaged NFS file storage。"],
  ["S3", "object storage。画像、log、backup、static Webなどで頻出。"],
  ["IOPS", "1秒あたりのI/O操作回数。storage performanceを示す主要指標。"],
  ["throughput", "単位時間あたりに転送できるdata量。MB/sなどで表す。"],
  ["io2 Block Express", "非常に高いIOPS、低latency、高durabilityを重視するEBS volume type。"],
  ["gp3", "容量とIOPS・throughputを独立設定できるgeneral purpose EBS volume type。"],

  // Databases and analytics
  ["Aurora Global Database", "Auroraを複数regionへreplicateし、global readとregion DRに使う構成。"],
  ["Aurora Serverless", "需要に合わせてdatabase capacityを自動調整するAurora構成。"],
  ["Aurora Backtrack", "対応Aurora clusterをbackup restoreなしで過去の時点へ巻き戻す機能。"],
  ["Point-in-Time Recovery", "自動backupから指定時刻の状態へ新しいDBをrestoreする機能。"],
  ["RDS Proxy", "applicationとRDS・Aurora間でDB connectionをpool・共有するmanaged proxy。"],
  ["Read Replica", "RDS・Auroraのread loadを逃がすreplica。Multi-AZとは目的が異なる。"],
  ["Multi-AZ", "複数AZにまたがるhigh availability構成。RDSではautomatic failover目的で頻出。"],
  ["DynamoDB global tables", "DynamoDB tableを複数regionへmulti-active replicateし、各regionでread・writeを受ける機能。"],
  ["partition key", "DynamoDBでitemのpartition配置を決めるprimary key要素。高cardinalityが負荷分散に重要。"],
  ["sort key", "同じpartition key内のitemを識別・並べ替えるcomposite primary key要素。"],
  ["hot partition", "特定partition keyへaccessが集中し、throughput不足やthrottlingを起こす状態。"],
  ["write sharding", "keyへsuffixなどを加え、writeを複数partition keyへ意図的に分散する手法。"],
  ["DynamoDB", "managed NoSQL DB。大規模・低latencyのkey-value・document用途。"],
  ["DAX", "DynamoDB Accelerator。DynamoDB readを高速化するin-memory cache。"],
  ["ElastiCache", "Redis・Memcached互換のmanaged cache。DB read load軽減などに使う。"],
  ["Aurora", "MySQL・PostgreSQL互換のhigh-performance managed RDB。"],
  ["RDS", "managed relational database service。"],
  ["Redshift", "DWH。大量dataの集計・分析向け。"],
  ["Athena", "S3上のdataをserverlessにSQL分析するservice。"],
  ["OpenSearch", "全文検索、log検索、検索結果のvisualizationに使うmanaged search service。"],
  ["Neptune", "graph構造と関係性の探索に使うmanaged graph DB。"],
  ["Timestream", "IoT telemetryなどtimestamp付きdataを扱うmanaged time-series DB。"],
  ["DWH", "Data Warehouse。大量dataを統合し、分析queryやBIに使う基盤。"],

  // Messaging and orchestration
  ["dead-letter queue", "規定回数失敗したmessageをsource queueから隔離し、後で調査・再処理するqueue。"],
  ["redrive policy", "SQSでmaxReceiveCountとdead-letter queueを指定し、失敗messageの移動条件を定義するpolicy。"],
  ["visibility timeout", "SQS consumerが受信したmessageを、処理中ほかのconsumerから一時的に見えなくする時間。"],
  ["SQS FIFO", "message順序と重複排除を重視するSQS queue type。"],
  ["DLQ", "Dead-Letter Queue。処理に繰り返し失敗したmessageを隔離するqueue。"],
  ["EventBridge archive", "EventBridge busのeventを保持し、後からreplayできる機能。"],
  ["EventBridge Scheduler", "指定時刻や繰り返し条件でAWS serviceを起動するserverless scheduler。"],
  ["FIFO", "First In, First Out。messageの順序を保つqueue方式。"],
  ["Step Functions", "複数stepの処理、branch、wait、retry、state管理を扱うworkflow service。"],
  ["EventBridge", "AWS・SaaS・独自applicationのeventをruleでroutingするevent bus。"],
  ["Kinesis Data Streams", "real-time dataをshardへ取り込み、複数consumerが処理するstreaming service。"],
  ["Kinesis Data Firehose", "streaming dataをS3やRedshiftなどへmanaged deliveryするservice。"],
  ["Firehose", "Kinesis Data Firehoseの短い呼び方。streaming dataのdeliveryを管理する。"],
  ["Kinesis", "real-time streaming dataのingest・processingに使うservice群。"],
  ["SQS", "queue。処理をためて非同期化し、systemを疎結合にする。"],
  ["SNS", "publish・subscribe notification。1つのeventを複数subscriberへ配信する。"],
  ["疎結合", "component同士の依存を弱め、片方の遅延や障害が全体へ波及しにくくする設計。"],

  // Resilience and disaster recovery
  ["Active-Active", "複数environmentを同時にproduction稼働させるDR・high availability構成。強いが高cost。"],
  ["Warm Standby", "縮小版production environmentを常時稼働させ、障害時にscale upするDR方式。"],
  ["Pilot Light", "DBや設定など中核を常時用意し、障害時にapplicationを起動するDR方式。"],
  ["Backup and Restore", "backupからrestoreするDR方式。低costだがrecoveryは遅い。"],
  ["AWS Elastic Disaster Recovery", "serverのblock-level dataをAWSへ継続複製し、障害時のrecovery instance起動を支援するサービス。"],
  ["RPO", "Recovery Point Objective。許容できるdata lossの時間。"],
  ["RTO", "Recovery Time Objective。許容できるservice停止時間。"],

  // Cost and purchase options
  ["Compute Savings Plans", "EC2 family・region変更やFargate・Lambdaにも柔軟に適用できるcompute使用量commit割引。"],
  ["EC2 Instance Savings Plans", "特定region・instance familyのEC2利用へ高い割引を適用するcommit plan。"],
  ["Reserved Instances", "長期安定利用に対する予約割引。EC2やRDSなどで利用する。"],
  ["Savings Plans", "1年・3年のcompute使用量commitによる割引。"],
  ["On-Demand", "長期commitなしで使った分だけ支払うpurchase option。短期・変動利用向け。"],
  ["Spot", "AWSの余剰capacityを安く使うEC2 purchase option。中断許容が前提。"],
  ["Dedicated Host", "物理host単位でEC2を専有し、socket・core単位のBYOL要件に対応しやすい。"],
  ["BYOL", "Bring Your Own License。保有licenseをcloud環境へ持ち込んで利用する方式。"],
  ["AWS Cost Anomaly Detection", "machine learningで通常と異なるcost増加を検出し、subscriptionで通知するservice。"],
  ["AWS Budgets", "実績または予測costがbudget thresholdへ達した際に通知するservice。"],
  ["Cost Explorer", "AWS costをservice別・期間別などで分析するservice。"],
  ["Compute Optimizer", "EC2やRDSなどのsize最適化recommendationを出すservice。"],
  ["AWS Backup", "EBS、RDS、EFSなど複数serviceのbackupをpolicyで集中管理するservice。"]
]);

window.SAA_GLOSSARY_BOUNDARY = Object.freeze({
  canWrap(source, offset, match) {
    const isAsciiWordChar = char => Boolean(char) && /[A-Za-z0-9_]/.test(char);
    const startsWithAsciiWord = /^[A-Za-z0-9_]/.test(match);
    const endsWithAsciiWord = /[A-Za-z0-9_]$/.test(match);
    if (startsWithAsciiWord && isAsciiWordChar(source[offset - 1])) return false;
    if (endsWithAsciiWord && isAsciiWordChar(source[offset + match.length])) return false;
    return true;
  },
});
